[package]
name = "telnetd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "telnetd"
path = "main.rs"

[dependencies]
strat9-syscall = { path = "../../syscall", features = ["userspace"] }
alloc-freelist = { path = "../../alloc-freelist" }
