[package]
name = "silo-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Guillaume Gielly <guillaume@gielly.fr>"]

[dependencies]

[profile.release]
panic = "abort"
strip = true
