[package]
name = "strate-init"
version = "0.1.0"
edition = "2024"

[dependencies]
# Strat9 Kernel integration
strat9-syscall = { path = "../syscall", features = ["userspace"] }
alloc-freelist = { path = "../alloc-freelist" }

[features]
default = []
